[workspace]
members = [
    "crates/main",
    "crates/networking",
    "crates/univariate-dkg",
    "crates/bivariate-dkg",
    "crates/types",
    "crates/nidkg"
]

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.dev.package.miracl_core_bls12381]
opt-level = 3
